INSERT ALL
  INTO Departments VALUES('Mathematical Sciences', 'Math')
  INTO Departments VALUES('Applied Mechanics','AM')
  INTO Departments VALUES('Applied Physics', 'AP')
  INTO Departments VALUES('Applied Information Technology', 'AIT')
  INTO Departments VALUES('Computer Science and Engineering', 'CSE')
  INTO Departments VALUES('Architecture', 'Arch')
  INTO Departments VALUES('Energy and Environment','ENV')
  INTO Departments VALUES('Civil and Environmental Engineering','CEE')
  INTO Programs VALUES('AUTOMATION AND MECHATRONICS ENGINEERING', 'TKAUT')
  INTO Programs VALUES('ENGINEERING PHYSICS', 'TKTFY')
  INTO Programs VALUES('SOFTWARE ENGINEERING', 'TKITE')
  INTO Programs VALUES('ARCHITECTURE', 'TKARK')
  INTO Programs VALUES('COMPUTER SCIENCE AND ENGINEERING', 'TKDAK')
  INTO Programs VALUES('COMPUTER ENGINEERING', 'TIDAL')
  INTO Programs VALUES('SYSTEMS, CONTROL AND MECHATRONICS','TKDAT')
  INTO Branches VALUES('SYSTEMS, CONTROL AND MECHATRONICS', 'MPSYS', 'TKDAT')
  INTO Branches VALUES('INTERACTION DESIGN AND TECHNOLOGIES', 'MPIDE', 'TKITE')
  INTO Branches VALUES('NUCLEAR ENGINEERING', 'MPNUE', 'TKTFY')
  INTO Branches VALUES('SOFTWARE ENGINEERING', 'MPSOF', 'TKITE')
  INTO Branches VALUES('SOFTWARE ENGINEERING', 'MPSOF', 'TIDAL')
  INTO Branches VALUES('SOFTWARE ENGINEERING', 'MPSOF', 'TKDAK')
  INTO Courses VALUES('TDA357', 'Databases', 100, 'CSE')
  INTO Courses VALUES('TDA545', 'Object-oriented programming', 100, 'CSE')
  INTO Courses VALUES('EDA344', 'Computer Communication', 100, 'CSE')
  INTO Courses VALUES('TDA596', 'Distributed Systems', 100, 'CSE')
  INTO Courses VALUES('EDA387', 'Computer Networks', 100, 'CSE')
  INTO Courses VALUES('DAT093', 'Introduction to Electronic Systems Design', 75, 'CSE')
  INTO Courses VALUES('DAT116', 'Mixed Signal Systems Design', 100, 'CSE')
  INTO Courses VALUES('TDA550', 'Object-oriented programming, advanced course', 100, 'CSE')
  INTO Courses VALUES('TMV200', 'Discrete mathematics', 100, 'AM')
  INTO Courses VALUES('TMV206', 'Linear algebra', 150, 'AM')
  INTO Courses VALUES('TDA361', 'Computer graphics', 130, 'AM')
  INTO Courses VALUES('KTK111', 'Chemistry for engineers', 100, 'CEE')
  INTO Courses VALUES('FFR166', 'Science of Environmental Change',100,'ENV')
  INTO Courses VALUES('FFY621', 'Physics for engineers', 85, 'AP')
  INTO Courses VALUES('FFR105', 'Stochastic Optimization Algorithms', 75, 'AP')
  INTO Courses VALUES('TDA383', 'Concurrent programming', 75, 'AIT')
  INTO Courses VALUES('DAT240', 'Model-driven engineering', 100, 'AIT')
  INTO Courses VALUES('TMV027', 'Finite Automata Theory and Formal Languages',75,'CSE')
  INTO LimitedCourses VALUES('TDA357', 2)
  INTO LimitedCourses VALUES('DAT116', 4)
  INTO LimitedCourses VALUES('DAT093',6 )
  INTO LimitedCourses VALUES('TDA550', 8)
  INTO LimitedCourses VALUES('TDA383',2)
  INTO Classifications VALUES('mathematical')
  INTO Classifications VALUES('research')
  INTO Classifications VALUES('seminar')
  INTO HasClassification VALUES('TMV200','mathematical')
  INTO HasClassification VALUES('TMV206','mathematical')
  INTO HasClassification VALUES('FFR105','research')
  INTO HasClassification VALUES('FFR166','seminar')
  INTO HasClassification VALUES('KTK111','seminar')
  INTO Requires VALUES('TDA596','EDA387')
  INTO Requires VALUES('EDA387','EDA344')
  INTO Requires VALUES('TDA550','TDA545')
  INTO Requires VALUES('TDA596','EDA344')
  INTO Requires VALUES('TDA361','TMV206')
  INTO MandatoryInProgram VALUES('TKITE','EDA387')
  INTO MandatoryInProgram VALUES('TKDAT','DAT093')
  INTO MandatoryinProgram VALUES('TKITE','TDA545')
  INTO MandatoryInProgram VALUES('TKITE','TDA357')
  INTO MandatoryInBranch VALUES('TKITE','MPIDE','TDA357')
  INTO MandatoryInBranch VALUES('TKITE','MPSOF','TDA550')
  INTO MandatoryInBranch VALUES('TKITE','MPSOF','TDA383')
  INTO MandatoryInBranch VALUES('TKITE','MPSOF','TMV027')
  INTO Recommends VALUES('TKITE','MPIDE','TDA357')
  INTO Recommends VALUES('TKITE','MPSOF','TDA357')
  INTO Recommends VALUES('TKITE', 'MPSOF', 'TDA383')
  INTO Recommends VALUES('TKDAT','MPSYS','DAT093')
  INTO Students VALUES('mohitg','Mohit Gupta', 'TIDAL', 'MPSOF')
  INTO Students VALUES('boonen','Sophie Boonen','TKITE', 'MPIDE')
  INTO Students VALUES('mynameis','My Name', 'TKDAT','MPSYS')
  INTO Students VALUES('samplper','Sample Person','TKDAK', 'MPSOF')
  INTO Students VALUES('imname','Imaginary Name','TKITE', 'MPSOF')
  INTO Students VALUES('bwayne','Bruce Wayne','TKITE', 'MPSOF')
  INTO Students VALUES('ckent','Clark Kent','TKITE', 'MPSOF')
  INTO Finishes VALUES('mohitg','EDA387','4')
  INTO Finishes VALUES('boonen','TDA357','U')
  INTO Finishes VALUES('mohitg','FFR166','3')
  INTO Finishes VALUES('bwayne','TDA357','5')
  INTO Finishes VALUES('ckent','DAT093','5')
  INTO Finishes VALUES('ckent','TDA383','4')
  INTO Finishes VALUES('ckent','TDA550','4')
  INTO Finishes VALUES('ckent','TDA545','5')
  INTO Finishes VALUES('ckent','EDA387','4')
  INTO Finishes VALUES('ckent','TMV200','4')
  INTO Finishes VALUES('ckent','EDA344','4')
  INTO Finishes VALUES('ckent','TMV027', '4')
  INTO Finishes VALUES('ckent','FFR105', '5')
  INTO Finishes VALUES('ckent','KTK111', '4') 
  INTO Finishes VALUES('imname','TDA357','U')
  INTO Finishes VALUES('mynameis','EDA387','U')
  INTO Finishes VALUES('ckent','TDA357','5')  
  INTO Takes VALUES('samplper','DAT093')
  INTO Takes VALUES('samplper','FFR166')
  INTO Takes VALUES('imname','TDA357')
  INTO Takes VALUES('imname','TDA383')
  INTO Takes VALUES('bwayne','TDA383')
  INTO Takes VALUES('samplper','TDA357')
  INTO Takes VALUES('mynameis', 'TDA357')
SELECT 1 FROM DUAL;

INSERT INTO Waits VALUES('mohitg','TDA383',QueueNumber.nextval);
INSERT INTO Waits VALUES('boonen','TDA383',QueueNumber.nextval);
INSERT INTO Waits VALUES('bwayne','TDA550',QueueNumber.nextval);
INSERT INTO Waits VALUES('samplper','DAT116',QueueNumber.nextval);
  
  
  
  
  
  
